import { PrismaClient } from "@prisma/client";
import * as dotenv from "dotenv";

dotenv.config();

const db = new PrismaClient();

async function seed() {
  console.log("Seeding food items...");

  await db.foodItem.deleteMany();

  await db.foodItem.createMany({
    data: [
      // STARTERS
      {
        name: "Ezogelin Çorbası",
        description: "Bulgur, kırmızı mercimek ve baharatlarla hazırlanmış geleneksel Türk çorbası",
        calories: 100,
        category: "main",
        keywords: ["ezogelin", "ezogelin çorbası"],
        isSaladBar: false,
      },
      {
        name: "Yayla Çorbası",
        description: "Yoğurt, pirinç ve nane ile hazırlanmış, soğuk günlerin vazgeçilmez Türk çorbası",
        calories: 150,
        category: "main",
        keywords: ["yayla", "yayla çorbası"],
        isSaladBar: false,
      },
      {
        name: "Yoğurt Çorbası",
        description: "Taze yoğurt ve pirinçle hazırlanmış, hafif ve besleyici geleneksel çorba",
        calories: 150,
        category: "main",
        keywords: ["yoğurt", "yoğurt çorbası"],
        isSaladBar: false,
      },
      {
        name: "Mercimek Çorbası",
        description: "Geleneksel Türk mutfağından kırmızı mercimek çorbası, limon ve kruton eşliğinde",
        calories: 75,
        category: "main",
        keywords: ["mercimek", "mercimek çorbası"],
        isSaladBar: false,
      },
      {
        name: "Anadolu Çorbası",
        description: "Sebzeler, bakliyat ve baharatlarla zenginleştirilmiş doyurucu Anadolu usulü çorba",
        calories: 146,
        category: "main",
        keywords: ["anadolu", "anadolu çorbası"],
        isSaladBar: false,
      },
      {
        name: "Tarhana Çorbası",
        description: "Geleneksel yöntemlerle kurutulmuş tarhana ile hazırlanmış, aromalı ve besleyici çorba",
        calories: 41,
        category: "main",
        keywords: ["tarhana", "tarhana çorbası"],
        isSaladBar: false,
      },
      {
        name: "Köylü Çorba",
        description: "Taze sebzeler ve tahıllarla hazırlanmış, köy usulü doyurucu çorba",
        calories: 143,
        category: "main",
        keywords: ["köylü", "köylü çorba", "köy çorbası"],
        isSaladBar: false,
      },
      {
        name: "Kremalı Mantar Çorbası",
        description: "Taze mantar ve krema ile hazırlanmış, kadifemsi dokulu lezzetli çorba",
        calories: 104,
        category: "main",
        keywords: ["mantar", "kremalı mantar", "kremalı mantar çorbası"],
        isSaladBar: false
      },
      {
        name: "Şehriyeli Tavuksuyu Çorba",
        description: "Ev yapımı tavuk suyu ve ince şehriye ile hazırlanmış, şifalı geleneksel çorba",
        calories: 132,
        category: "main",
        keywords: ["tavuksuyu", "şehriyeli tavuksuyu", "tavuk suyu çorbası"],
        isSaladBar: false,
      },
      {
        name: "Köz Domates Çorba",
        description: "Közlenmiş domateslerle hazırlanmış, dumanlı aromasıyla özel çorba",
        calories: 154,
        category: "main",
        keywords: ["köz domates", "domates çorbası", "köz domates çorba"],
        isSaladBar: false,
      },
      {
        name: "Arpa Şehriye Çorba",
        description: "Arpa şehriyesi ve sebzelerle hazırlanmış, hafif ve doyurucu çorba",
        calories: 80,
        category: "main",
        keywords: ["arpa", "arpa şehriye", "arpa şehriye çorba"],
        isSaladBar: false,
      },
      {
        name: "Mahluta Çorbası",
        description: "Karışık bakliyat ve tahıllarla hazırlanmış, protein açısından zengin geleneksel çorba",
        calories: 82,
        category: "main",
        keywords: ["mahluta", "mahluta çorbası"],
        isSaladBar: false,
      },

      // ANA YEMEKLER
      {
        name: "Et Döner",
        description: "Özel baharatlarla marine edilmiş, döner usulü pişirilmiş lezzetli et",
        calories: 320,
        category: "main",
        keywords: ["döner", "et döner"],
        isSaladBar: false,
      },
      {
        name: "Etli Kuru Fasulye",
        description: "Dana etiyle birlikte pişirilmiş, geleneksel Türk usulü kuru fasulye",
        calories: 304,
        category: "main",
        keywords: ["kuru fasulye", "etli kuru fasulye", "fasulye"],
        isSaladBar: false,
      },
      {
        name: "Karışık Izgara",
        description: "2 adet köfte ve 1 adet tavuk olmak üzere közde pişirilmiş karışık ızgara tabağı",
        calories: 400,
        category: "main",
        keywords: ["karışık ızgara", "ızgara", "karışık izgara"],
        isSaladBar: false,
      },
      {
        name: "Mantı",
        description: "El açması hamurla hazırlanmış, yoğurt ve domates soslu geleneksel Türk mantısı",
        calories: 443,
        category: "main",
        keywords: ["mantı"],
        isSaladBar: false,
      },
      {
        name: "Susamlı Tavuk But",
        description: "Susam kaplı, fırında çıtır çıtır pişirilmiş lezzetli tavuk but",
        calories: 300,
        category: "main",
        keywords: ["susamlı tavuk", "tavuk but", "susamlı tavuk but"],
        isSaladBar: false,
      },
      {
        name: "Dana Haşlama",
        description: "Sebzelerle birlikte yavaş pişirilmiş, yumuşacık ve besleyici dana haşlama",
        calories: 246,
        category: "main",
        keywords: ["haşlama", "dana haşlama"],
        isSaladBar: false,
      },
      {
        name: "Kıymalı Biber Dolması",
        description: "Kıyma ve pirinç harmanıyla doldurulmuş, domates sosunda pişirilmiş biber dolması",
        calories: 343,
        category: "main",
        keywords: ["dolma", "biber dolması", "kıymalı biber dolması"],
        isSaladBar: false,
      },
      {
        name: "İnegöl Köfte",
        description: "Geleneksel İnegöl usulü hazırlanmış, ızgarada pişirilmiş köfte (3 adet)",
        calories: 672,
        category: "main",
        keywords: ["inegöl", "inegöl köfte"],
        isSaladBar: false,
      },
      {
        name: "Karnıyarık",
        description: "Kıymalı iç harçla doldurulmuş, fırında pişirilmiş geleneksel karnıyarık",
        calories: 401,
        category: "main",
        keywords: ["karnıyarık", "musakka", "karnıyarık musakka"],
        isSaladBar: false,
      },
      {
        name: "Piliç Çökertme Kebabı",
        description: "İnce dilimlenmiş piliç eti, yoğurt ve tereyağlı sos ile servis edilen kebap",
        calories: 450,
        category: "main",
        keywords: ["çökertme", "piliç çökertme", "çökertme kebabı"],
        isSaladBar: false,
      },
      {
        name: "Fırında Filiz Kebap",
        description: "Özel baharatlarla marine edilmiş, fırında yavaş pişirilmiş filiz kebap",
        calories: 459,
        category: "main",
        keywords: ["filiz kebap", "fırında filiz", "filiz"],
        isSaladBar: false,
      },
      {
        name: "Kaşarlı Kıymalı Ispanak",
        description: "Kıyma ve ıspanakla hazırlanmış, üzeri kaşarla kaplı fırın yemeği",
        calories: 300,
        category: "main",
        keywords: ["ıspanak", "kaşarlı ıspanak", "kıymalı ıspanak"],
        isSaladBar: false,
      },
      {
        name: "Çıtır Tavuk",
        description: "Özel un karışımıyla kaplı, dışı çıtır içi yumuşak kızartma tavuk",
        calories: 364,
        category: "main",
        keywords: ["çıtır tavuk", "tavuk"],
        isSaladBar: false,
      },
      {
        name: "Etli Barbunya",
        description: "Dana etiyle birlikte pişirilmiş, geleneksel usulü barbunya pilaki",
        calories: 300,
        category: "main",
        keywords: ["barbunya", "etli barbunya"],
        isSaladBar: false,
      },
      {
        name: "Kıymalı Sandal Sefası",
        description: "Kıyma ve sebzelerle hazırlanmış, geleneksel Türk usulü fırın yemeği",
        calories: 350,
        category: "main",
        keywords: ["sandal sefası", "kıymalı sandal", "sandal"],
        isSaladBar: false,
      },
      {
        name: "Soslu Köfte",
        description: "Domates sosunda pişirilmiş, yumuşacık ev yapımı köfte (3 adet)",
        calories: 300,
        category: "main",
        keywords: ["soslu köfte", "köfte"],
        isSaladBar: false,
      },
      {
        name: "Etli Fırın Türlü",
        description: "Mevsim sebzeleri ve dana etiyle hazırlanmış, fırında pişirilmiş türlü",
        calories: 405,
        category: "main",
        keywords: ["türlü", "fırın türlü", "etli türlü"],
        isSaladBar: false,
      },
      {
        name: "Orman Kebabı",
        description: "Mantar ve sebzelerle birlikte pişirilmiş, aromatik baharatlı et yemeği",
        calories: 270,
        category: "main",
        keywords: ["orman kebabı", "orman"],
        isSaladBar: false,
      },
      {
        name: "Etli Maraş Usulü Taze Fasulye",
        description: "Maraş yöresine özgü, dana etiyle pişirilmiş taze fasulye yemeği",
        calories: 288,
        category: "main",
        keywords: ["taze fasulye", "maraş fasulye", "etli taze fasulye"],
        isSaladBar: false,
      },
      {
        name: "Çıtır Kanat",
        description: "Özel baharatlarla marine edilmiş, çıtır kızarmış tavuk kanat, patates eşliğinde",
        calories: 600,
        category: "main",
        keywords: ["kanat", "çıtır kanat", "tavuk kanat"],
        isSaladBar: false,
      },

      // PİLAV & MAKARNA
      {
        name: "Pirinç Pilavı",
        description: "Tereyağlı buharda pişirilmiş Türk pilavı",
        calories: 389,
        category: "main",
        keywords: ["pilav", "pirinç pilavı", "pirinç"],
        isSaladBar: false,
      },
      {
        name: "Arpa Şehriyeli Pirinç Pilavı",
        description: "Arpa şehriyesiyle zenginleştirilmiş, tereyağlı pirinç pilavı",
        calories: 422,
        category: "main",
        keywords: ["arpa şehriyeli pilav", "arpa pilav"],
        isSaladBar: false,
      },
      {
        name: "Tel Şehriyeli Pirinç Pilavı",
        description: "İnce tel şehriyesiyle hazırlanmış, altın rengi kavurmalı pirinç pilavı",
        calories: 422,
        category: "main",
        keywords: ["tel şehriyeli pilav", "şehriyeli pilav", "tel pilav"],
        isSaladBar: false,
      },
      {
        name: "Şehriyeli Bulgur Pilavı",
        description: "Şehriye ile birlikte pişirilmiş, hafif ve besleyici bulgur pilavı",
        calories: 274,
        category: "main",
        keywords: ["bulgur", "bulgur pilavı", "şehriyeli bulgur"],
        isSaladBar: false,
      },
      {
        name: "Sebzeli Bulgur Pilavı",
        description: "Mevsim sebzeleriyle zenginleştirilmiş, sağlıklı bulgur pilavı",
        calories: 306,
        category: "main",
        keywords: ["sebzeli bulgur", "sebzeli pilav"],
        isSaladBar: false,
      },
      {
        name: "Peynirli Makarna",
        description: "Kremsi peynir sosuyla hazırlanmış, doyurucu fırın makarna",
        calories: 332,
        category: "main",
        keywords: ["peynirli makarna", "makarna"],
        isSaladBar: false,
      },
      {
        name: "Soslu Makarna",
        description: "Domates bazlı özel sosla hazırlanmış, geleneksel Türk usulü makarna",
        calories: 241,
        category: "main",
        keywords: ["soslu makarna", "makarna"],
        isSaladBar: false,
      },

      // BÖREK & HAMUR İŞLERİ
      {
        name: "Peynirli Tepsi Börek",
        description: "Beyaz peynir harçlı, fırında altın rengi pişirilmiş çıtır tepsi böreği",
        calories: 300,
        category: "main",
        keywords: ["tepsi börek", "peynirli börek", "börek"],
        isSaladBar: false,
      },
      {
        name: "Su Böreği",
        description: "Haşlanmış yufkalarla hazırlanmış, peynirli geleneksel Türk su böreği",
        calories: 300,
        category: "main",
        keywords: ["su böreği", "börek"],
        isSaladBar: false,
      },
      {
        name: "Peynirli Milföy Börek",
        description: "Beyaz peynir dolgulu, çıtır milföy hamurlu fırın böreği",
        calories: 620,
        category: "main",
        keywords: ["milföy", "milföy börek", "peynirli milföy"],
        isSaladBar: false,
      },

      // TATLILAR
      {
        name: "Cevizli Kadayıf",
        description: "Ceviz dolgulu, şerbetli geleneksel Türk tatlısı kadayıf",
        calories: 300,
        category: "dessert",
        keywords: ["kadayıf", "cevizli kadayıf"],
        isSaladBar: false,
      },
      {
        name: "Cevizli Baklava",
        description: "Ceviz dolgulu, bal şerbetiyle hazırlanmış ince katlı Türk baklavası (2 adet)",
        calories: 207,
        category: "dessert",
        keywords: ["baklava", "cevizli baklava"],
        isSaladBar: false,
      },
      {
        name: "Fırın Sütlaç",
        description: "Fırında pişirilmiş geleneksel Türk sütlacı, tarçın ile servis edilir",
        calories: 220,
        category: "dessert",
        keywords: ["sütlaç", "fırın sütlaç"],
        isSaladBar: false,
      },
      {
        name: "İrmik Helvası",
        description: "Tereyağında kavrulmuş irmik, şeker şurubu ile hazırlanmış geleneksel helva",
        calories: 338,
        category: "dessert",
        keywords: ["helva", "irmik helvası", "irmik"],
        isSaladBar: false,
      },
      {
        name: "Sade Kek",
        description: "Günlük taze pişirilmiş, yumuşak ve hafif sade kek",
        calories: 200,
        category: "dessert",
        keywords: ["kek", "sade kek"],
        isSaladBar: false,
      },
      {
        name: "Çıtır Kadayıflı Kup",
        description: "Çıtır kadayıf, dondurma ve şerbetle hazırlanmış özel kup tatlısı",
        calories: 187,
        category: "dessert",
        keywords: ["kadayıflı kup", "kup", "çıtır kadayıf"],
        isSaladBar: false,
      },

      // YAN ÜRÜNLER (category: "starter" — sides and salads)
      {
        name: "Şakşuka",
        description: "Kızartılmış patlıcan, biber ve domates sosuyla hazırlanmış geleneksel meze",
        calories: 71,
        category: "starter",
        keywords: ["şakşuka"],
        isSaladBar: false,
      },
      {
        name: "Cacık",
        description: "Taze salatalık, sarımsak ve nane ile hazırlanmış soğuk yoğurtlu meze",
        calories: 66,
        category: "starter",
        keywords: ["cacık"],
        isSaladBar: false,
      },
      {
        name: "Yoğurt",
        description: "Taze günlük yoğurt (100 gr)",
        calories: 62,
        category: "starter",
        keywords: ["yoğurt"],
        isSaladBar: false,
      },
      {
        name: "Mevsim Salata",
        description: "Taze mevsim yeşillikleri, domates ve salatalıktan oluşan günlük salata",
        calories: 100,
        category: "starter",
        keywords: ["mevsim salata", "salata", "mevsim salatası"],
        isSaladBar: false,
      },
      {
        name: "Mevsim Meyve",
        description: "Günlük taze mevsim meyveleri",
        calories: 78,
        category: "dessert",
        keywords: ["meyve", "mevsim meyve"],
        isSaladBar: false,
      },
      {
        name: "Ayran",
        description: "Günlük taze yoğurttan yapılan soğuk servis edilen geleneksel Türk içeceği",
        calories: 58,
        category: "drink",
        keywords: ["ayran"],
        isSaladBar: false,
      },
      {
        name: "Meşrubat",
        description: "Soğuk içecek seçenekleri",
        calories: 100,
        category: "drink",
        keywords: ["meşrubat", "içecek"],
        isSaladBar: false,
      },
      {
        name: "Karışık Komposto",
        description: "Mevsim meyvelerinden hazırlanmış, şekerli geleneksel Türk kompostosu",
        calories: 106,
        category: "drink",
        keywords: ["komposto", "karışık komposto"],
        isSaladBar: false,
      },
      {
        name: "Hamidiye Su",
        description: "Hamidiye doğal kaynak suyu (80 ml)",
        calories: 0,
        category: "drink",
        keywords: ["su", "hamidiye", "hamidiye su"],
        isSaladBar: true,
      },
      {
        name: "Eker Yoğurt",
        description: "Eker günlük taze yoğurt (150 gr)",
        calories: 93,
        category: "starter",
        keywords: ["yoğurt", "eker yoğurt", "eker"],
        isSaladBar: true,
      },
      {
        name: "Çay & Kahve",
        description: "Çay ve kahve standı — sınırsız ikram",
        calories: 5,
        category: "drink",
        keywords: ["çay", "kahve", "çay kahve", "içecek"],
        isSaladBar: true,
      },
      {
        name: "Ekmek",
        description: "Günlük taze pişirilmiş, küçük boy ekmek (1 paket)",
        calories: 65,
        category: "starter",
        keywords: ["ekmek", "küçük ekmek"],
        isSaladBar: true,
      },
    ],
  });

  console.log("✅ Seeded successfully");
  await db.$disconnect();
}

seed().catch((e) => {
  console.error(e);
  db.$disconnect();
  process.exit(1);
});
